name: asset_gen
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.4.1 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  dartx: ^1.2.0
  path: ^1.9.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^3.0.0
