name: gsdatabase
description: Dart library to load and parse my custom gsdatabase
version: 1.2.2
# repository: https://github.com/exbraiin/dart-gsdatabase

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # dartx: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  build: ^4.0.0
  source_gen: ^4.0.1
  analyzer: ^8.1.1
  build_runner: ^2.4.7
